# Configuración automática de Prometheus como datasource en Grafana
# Compatible con Mac (desarrollo) y Windows Server 2025 (producción)

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
